export const TabData = [
  {
    id: 1,
    title: 'Cadastros Pessoas',
    heading:
      'Todo o cadastro de clientes, funcionários, fornecedores, transportes, convenio, cooperados e usuários em um só lugar. Você pode cadastrar pessoas físicas e jurídicas, com informações detalhadas e foto. Além disso, é possivel cadastrar dados do transportador, como placa e dados do veículo, motorista e documentos, e muito mais!',
    imageSrc: '/images/Cadastro.png',
    items: [
      'Cadastro de funcionários, usuários, clientes e fornecedores',
      'Histórico de Cliente (acesso fácil)',
      'Cadastro com CNPJ automático',
      'Cadastro de multiplos endereços',
      'Preenchimento automatico de endereço por CEP',
      'Controle de situação de cliente',
      'Classes de clientes (juros e multas)',
      'Ajuste de limites',
      'Controle de pessoas autorizadas',
      'Inserção de foto',
    ],
  },
  {
    id: 2,
    title: 'Produtos / Serviços',
    heading:
      'Você pode cadastrar produtos e serviços, com informações detalhadas e foto. Além disso, é possivel cadastrar código de barras e consultar no GTIN. É possível cadastrar várias seções, marcas, modelos, cors e tamanhos para cada produto. Você pode controlar a unidade de medida principal e secundária com códigos de barras diferentes e muito mais!',
    imageSrc: '/images/Produto.png',
    items: [
      'Cadastro de produtos e serviços',
      'Consulta de GTIN (Código de barras)',
      'Controle de seção, marca, modelo, cor e tamanho',
      'Unidade de medida principal e secundária',
      'Locação',
      'Histórico de preços',
      'Histórico de entradas',
      'Movimento de estoque',
      'Detalhamento de custo (Mark up)',
      'Controle de tributação por UF',
      'Tabela de preço',
    ],
  },
  {
    id: 3,
    title: 'Pedido de venda',
    heading:
      'No pedido de venda você pode fazer orçamentos, ordem de serviços e vendas de forma prática e simples, todos possuem comprovantes ao fechar o pedido. Você pode parcelar o pagamento, gerar duplicata, comissão de vendas, gerar documentos fiscais, controle de entrega e trocas.',
    imageSrc: '/images/Vendas.png',
    items: [
      'Prazo de pagamento',
      'Parcelamento personalizado',
      'Tabela de preço',
      'Inserção de multiplos itens',
      'Movimentação de estoque e financeiro',
      'Controle de entrega',
      'Trocas',
      'Comissão de vendas',
      'Geração de NFC-e e NF-e',
      'Impressão de comprovante e duplicata',
    ],
  },
  {
    id: 4,
    title: 'Ordem de Serviços',
    heading:
      'Ordem de Serviço é um tipo de pedido onde você pode lançar produtos e serviços realizados e gerar documentos fiscais separados por NF-e e NFS-e (Nota Fiscal de Serviço Eletrônica).',
    imageSrc: '/images/OS.png',
    items: [
      'Lançamento de produtos e serviços',
      'Cadastro e acompanhamento de objeto',
      'Movimentação de estoque e financeiro',
      'Geração de NFS-e',
      'Impressão de comprovante',
      'Agenda de serviços',
    ],
  },
  {
    id: 5,
    title: 'PDV',
    heading:
      'Conhecido como Ponto de Vendas, mais utilizados em supermercados. O PDV é um software que permite a realização de vendas rápidas com emissão de NFC-e (Nota Fiscal do Consumidor Eletrônica). Possui integração com TEF, balança, gaveta, vale troco e pagamento com QR-Code PIX,e emissão de movimento de caixa por turno.',
    imageSrc: '/images/PDV.png',
    items: [
      'Emissão de NFC-e',
      'Abertura e fechamento de caixa por turno',
      'Integração com TEF',
      'Integração com balança e gaveta',
      'Emissão de vale troco',
      'Pagamento com QR-Code PIX',
    ],
  },
  {
    id: 6,
    title: 'NF-e',
    heading:
      'As notas podem serem emitidas de forma simplificada, com visualização de espelho e podendo ser editadas para correções rápidsa e fáceis antes da transmissão.',
    imageSrc: '/images/NFe.png',
    items: [
      'Emissão de NF-e',
      'Nota conjugada com produtos e serviços',
      'Nota de devolução e remessa',
      'Devolução de venda simplificado',
      'Autorização NFC-e pendentes',
      'Cancelamento de NF-e simplificado',
      'Emissão de CC-e simplificado',
      'Informações complementares',
      'Visualização do espelho da nota',
    ],
  },
  {
    id: 7,
    title: 'NFS-e',
    heading:
      'Nota Fiscal de Serviço é um documento fiscal especifico para prestadores de serviços. A NFS-e é emitida pelo MIDAS com integração com o software do portal municipal.',
    imageSrc: '/images/NSFe.png',
    items: [
      'Emissão de NFS-e simplificado',
      'Configuração de tributação e retenção',
      'Integração com portal municipal',
      'Cancelamento de NFS-e simplificado',
    ],
  },
  {
    id: 8,
    title: 'Central de Caixa',
    heading:
      'A central de caixa permite que você coloque um funcionário de caixa para controle sobre todas as pré-vendas e orçamentos feitos nos balcões, agilizando o recebimentos, fechamento de caixa e abrimento de caixa, emissões de documentos fiscais e relatórios.',
    imageSrc: '/images/Central.png',
    items: [
      'Fechamento de pedido pre-venda e orçamento',
      'Lançamento de sangria e suprimento',
      'Emissão de NFC-e e NF-e',
      'Fechamento e abrimento de caixa',
      'Movimentação de estoque',
      'Movimentação financeira',
    ],
  },
  {
    id: 9,
    title: 'Entradas / Compras',
    heading:
      'Lançamento de notas pratico com download dos XML e manifestação de notas. Além disso, é possível converter unidade de medida, atualizar custo e preço de venda, lançar produtos com ICMS-ST e muito mais!',
    imageSrc: '/images/Entrada.png',
    items: [
      'Importação de XML',
      'Download de XML',
      'Manifestar NF-e',
      'Conversor de unidade',
      'Atualização de custo e preço de venda',
      'Movimentação financeira',
      'Movimentação de estoque',
      'ICMS-ST',
    ],
  },
  {
    id: 10,
    title: 'Relatórios',
    heading:
      'O MIDAS conta com mais de 100 relatórios específicos com filtros e formatos personalizados ao salvar em PDF, Excel e Word.',
    imageSrc: '/images/Relatorios.png',
    items: [
      'Movimento e giro de produtos',
      'Movimentação de caixa',
      'Contas a pagar / receber',
      'Margem de lucro por venda',
      'DRE',
      'Curva ABC',
      'Inventário',
      'Sugestão de preço, compra e produção',
    ],
  },
  {
    id: 11,
    title: 'Industrialização',
    heading:
      'Tenha controle da produção dos produtos com lançamento de insumos e materias primas com controle de estoque e custos.  ',
    imageSrc: '/images/Transformacao.png',
    items: [
      'Cadastro de matéria prima e produto acabado',
      'Tabela de custos',
      'Movimentação de estoque',
      'Sugestão de produção',
      'Relatório demonstrativo',
    ],
  },
]
