export const TabData = [
  {
    value: 'tab1',
    title: 'Cadastros',
    heading: 'Cadastro de Pessoas',
    imageSrc: '/images/Cadastro.png',
    items: [
      'Cadastro de funcionários, usuários, clientes e fornecedores',
      'Histórico de Cliente (acesso fácil)',
      'Cadastro com CNPJ automático',
      'Cadastro de multiplos endereços',
      'Preenchimento automatico de endereço por CEP',
      'Controle de situação de cliente',
      'Classes de clientes (juros e multas)',
      'Ajuste de limites',
      'Controle de pessoas autorizadas',
      'Inserção de foto',
    ],
  },
  {
    value: 'tab2',
    title: 'Produtos/Serviços',
    heading: 'Produtos / Serviços',
    imageSrc: '/images/Produto.png',
    items: [
      'Cadastro de produtos e serviços',
      'Consulta de GTIN (Código de barras)',
      'Controle de seção, marca, modelo, cor e tamanho',
      'Unidade de medida principal e secundária',
      'Locação',
      'Histórico de preços',
      'Histórico de entradas',
      'Movimento de estoque',
      'Detalhamento de custo (Mark up)',
      'Controle de tributação por UF',
      'Tabela de preço',
    ],
  },
  {
    value: 'tab3',
    title: 'Pedido de venda',
    heading: 'Saídas / Vendas',
    imageSrc: '/images/Vendas.png',
    items: [
      'Prazo de pagamento',
      'Parcelamento personalizado',
      'Tabela de preço',
      'Inserção de multiplos itens',
      'Movimentação de estoque e financeiro',
      'Controle de entrega',
      'Trocas',
      'Comissão de vendas',
      'Geração de NFC-e e NF-e',
      'Impressão de comprovante e duplicata',
    ],
  },
  {
    value: 'tab4',
    title: 'Ordem de Serviços',
    heading: 'Ordem de Serviço',
    imageSrc: '/images/OS.png',
    items: [
      'Lançamento de produtos e serviços',
      'Cadastro e acompanhamento de objeto',
      'Movimentação de estoque e financeiro',
      'Geração de NFS-e',
      'Impressão de comprovante',
      'Agenda de serviços',
    ],
  },
  {
    value: 'tab5',
    title: 'PDV',
    heading: 'Ponto de Vendas',
    imageSrc: '/images/PDV.png',
    items: [
      'Emissão de NFC-e',
      'Abertura e fechamento de caixa por turno',
      'Integração com TEF',
      'Integração com balança e gaveta',
      'Emissão de vale troco',
      'Pagamento com QR-Code PIX',
    ],
  },
  {
    value: 'tab6',
    title: 'NF-e',
    heading: 'Nota Fiscal Eletronica',
    imageSrc: '/images/NFe.png',
    items: [
      'Emissão de NF-e',
      'Nota conjugada com produtos e serviços',
      'Nota de devolução e remessa',
      'Devolução de venda simplificado',
      'Autorização NFC-e pendentes',
      'Cancelamento de NF-e simplificado',
      'Emissão de CC-e simplificado',
      'Informações complementares',
      'Visualização do espelho da nota',
    ],
  },
  {
    value: 'tab7',
    title: 'NFS-e',
    heading: 'Nota Fiscal de Serviço',
    imageSrc: '/images/NSFe.png',
    items: [
      'Emissão de NFS-e simplificado',
      'Configuração de tributação e retenção',
      'Integração com portal municipal',
      'Cancelamento de NFS-e simplificado',
    ],
  },
  {
    value: 'tab8',
    title: 'Central de Caixa',
    heading: 'Central de Caixa',
    imageSrc: '/images/Central.png',
    items: [
      'Fechamento de pedido pre-venda e orçamento',
      'Lançamento de sangria e suprimento',
      'Emissão de NFC-e e NF-e',
      'Fechamento e abrimento de caixa',
      'Movimentação de estoque',
      'Movimentação financeira',
    ],
  },
  {
    value: 'tab9',
    title: 'Entradas/Compras',
    heading: 'Entradas / Compras',
    imageSrc: '/images/Entrada.png',
    items: [
      'Importação de XML',
      'Download de XML',
      'Manifestar NF-e',
      'Conversor de unidade',
      'Atualização de custo e preço de venda',
      'Movimentação financeira',
      'Movimentação de estoque',
      'ICMS-ST',
    ],
  },
  {
    value: 'tab10',
    title: 'Relatórios',
    heading: 'Relatórios',
    imageSrc: '/images/Relatorios.png',
    items: [
      'Movimento e giro de produtos',
      'Movimentação de caixa',
      'Contas a pagar / receber',
      'Margem de lucro por venda',
      'DRE',
      'Curva ABC',
      'Inventário',
      'Sugestão de preço, compra e produção',
    ],
  },
  {
    value: 'tab11',
    title: 'Industrialização',
    heading: 'Industrialização',
    imageSrc: '/images/Transformacao.png',
    items: [
      'Cadastro de matéria prima e produto acabado',
      'Tabela de custos',
      'Movimentação de estoque',
      'Sugestão de produção',
      'Relatório demonstrativo',
    ],
  },
]
